### PR TITLE
Correct measurement data types

### LINKED ISSUE #10: Use correct data types for columns containing air quality measurements
So that we can work with and doc calculations on the data.

We'll have to migrate the existing data.

### PR DESCRIPTION
**Pull request by henare**
The goal of this pull request is to fix #10 by changing the data type of the columns we're storing measurements in from varchar to float. To get there we needed to shave a few yaks :goat: 

* [Extract scraper](https://github.com/equivalentideas/westconnex_M4_East_Air_Quality_Monitoring/commit/6401b2ebbf447d822b6dd2f1ad84a7d7227d79e2) into a flimsy class so we can [test](https://github.com/equivalentideas/westconnex_M4_East_Air_Quality_Monitoring/commit/3d8b58140943f83b90a73bc9316fcbeea5eb49de) changes to the utility methods we already had in place
* [Change](https://github.com/equivalentideas/westconnex_M4_East_Air_Quality_Monitoring/commit/cf45a5f7aacfd894683a79a255bd9a22dc88569a) missing readings from being stored as '-' to `nil` (and add a migration to [fix existing values](https://github.com/equivalentideas/westconnex_M4_East_Air_Quality_Monitoring/commit/87f571414f0dfae5bc39521f40c6f1edbe796d9c))
* Then finally, [change the columns](https://github.com/equivalentideas/westconnex_M4_East_Air_Quality_Monitoring/commit/5624b43be5d80d57f59d3f610df0f5769d084a1c)

### CODE REVIEW

**Comment by henare** [comment]
@equivalentideas thanks for reviewing this :male_detective:

That's a good idea to check some summary results. I was planning to diff the CSV but we're expecting changes, making it hard to accurately do.

I've added a couple of rake tasks to do these checks in 76e3fdb. Once this has been successfully deployed we can remove these tasks.

**Comment by henare** [comment]
That's now deployed :tada: 

It didn't go as smoothly as I'd hoped. When I first deployed it (database was backed up as b014) the average values didn't match. I quickly realised that it was because I wasn't excluding the old nil fields, that were strings set to '-', from the average calculation.

So first of all I rolled back the change and restored the database backup.

```
# check change to master has been deployed
$ heroku releases
[snip]

# create backup
$ heroku pg:backups:capture
Starting backup of postgresql-tapered-78612... done

Use Ctrl-C at any time to stop monitoring progress; the backup will continue running.
Use heroku pg:backups:info to check progress.
Stop a running backup with heroku pg:backups:cancel.

Backing up DATABASE to b014... done

# pre-migration check
$ heroku run 'bundle exec rake statistics:temp:pull_request_40:ruby'
Running bundle exec rake statistics:temp:pull_request_40:ruby on ⬢ westconnex-m4-east-air-quality... up, run.1963 (Free)
pm2_5_concentration_ug_per_m3: 14.8767660911
pm10_concentration_ug_per_m3: 24.8006568619
co_concentration_ppm: 0.2292439891
no2_concentration_ppm: 0.0140242915

# run migration
$ time heroku run 'bundle exec rake db:migrate'
Running bundle exec rake db:migrate on ⬢ westconnex-m4-east-air-quality... up, run.6223 (Free)
Migrating database to latest version

real	0m11.555s
user	0m0.435s
sys	0m0.030s

# post-migration check. hrrm, that's not the same!
$ heroku run 'bundle exec rake statistics:temp:pull_request_40:ruby'
Running bundle exec rake statistics:temp:pull_request_40:ruby on ⬢ westconnex-m4-east-air-quality... up, run.4277 (Free)
pm2_5_concentration_ug_per_m3: 15.6039084843
pm10_concentration_ug_per_m3: 26.0139836201
co_concentration_ppm: 0.2515676852
no2_concentration_ppm: 0.0147628615
$ heroku run 'bundle exec rake statistics:temp:pull_request_40:sql'
Running bundle exec rake statistics:temp:pull_request_40:sql on ⬢ westconnex-m4-east-air-quality... up, run.6289 (Free)
pm2_5_concentration_ug_per_m3: 15.6039084843
pm10_concentration_ug_per_m3: 26.0139836201
co_concentration_ppm: 0.2515676852
no2_concentration_ppm: 0.0147628615

# rollback release
$ heroku releases
=== westconnex-m4-east-air-quality Releases - Current: v41
[snip]
$ heroku rollback v40
Rolling back ⬢ westconnex-m4-east-air-quality to v40... done, v42
 ▸    Rollback affects code and config vars; it doesn't add or remove addons.
 ▸    To undo, run: heroku rollback v41

# restore backup
$ heroku pg:backups:restore
 ▸    WARNING: Destructive Action
 ▸    This command will affect the app westconnex-m4-east-air-quality
 ▸    To proceed, type westconnex-m4-east-air-quality or re-run this command with --confirm westconnex-m4-east-air-quality

> westconnex-m4-east-air-quality
Starting restore of b014 to postgresql-tapered-78612... done

Use Ctrl-C at any time to stop monitoring progress; the backup will continue restoring.
Use heroku pg:backups to check progress.
Stop a running restore with heroku pg:backups:cancel.

Restoring... done
```

I then [created a change](https://github.com/equivalentideas/westconnex_M4_East_Air_Quality_Monitoring/commit/65e5a954b69fb5e2eaa5b4bf624dba33cb3fad73) to exclude those from the calculation and pushed it straight to master and re-did the deployment.

That also didn't quite go to plan as I didn't test the updated rake task against the new database so it failed when I ran it after the deployment. Instead of going through the whole dance again I just ran that check on the console and verified it was working, woo :sparkles: 

```
# check change to master has been deployed
$ heroku releases
[snip]

# run backup
$ heroku pg:backups:capture
Starting backup of postgresql-tapered-78612... done

Use Ctrl-C at any time to stop monitoring progress; the backup will continue running.
Use heroku pg:backups:info to check progress.
Stop a running backup with heroku pg:backups:cancel.

Backing up DATABASE to b016... done

# pre-migration check
$ heroku run 'bundle exec rake statistics:temp:pull_request_40:ruby'
Running bundle exec rake statistics:temp:pull_request_40:ruby on ⬢ westconnex-m4-east-air-quality... up, run.6543 (Free)
pm2_5_concentration_ug_per_m3: 15.6022786346
pm10_concentration_ug_per_m3: 26.0173114413
co_concentration_ppm: 0.2515300943
no2_concentration_ppm: 0.0147627929

# run migration
$ time heroku run 'bundle exec rake db:migrate'
Running bundle exec rake db:migrate on ⬢ westconnex-m4-east-air-quality... up, run.6722 (Free)
Migrating database to latest version

real	0m10.956s
user	0m0.468s
sys	0m0.041s

# post migration check - throws exception, arrg!
$ heroku run 'bundle exec rake statistics:temp:pull_request_40:ruby'
Running bundle exec rake statistics:temp:pull_request_40:ruby on ⬢ westconnex-m4-east-air-quality... up, run.3478 (Free)
rake aborted!
Sequel::DatabaseError: PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type double precision: "-"
LINE 1: ..."aqm_records" WHERE ("pm2_5_concentration_ug_per_m3" != '-')
                                                                   ^
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/adapters/postgres.rb:146:in `async_exec'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/adapters/postgres.rb:146:in `block in execute_query'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/database/logging.rb:38:in `log_connection_yield'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/adapters/postgres.rb:146:in `execute_query'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/adapters/postgres.rb:134:in `block in execute'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/adapters/postgres.rb:110:in `check_disconnect_errors'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/adapters/postgres.rb:134:in `execute'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/adapters/postgres.rb:456:in `_execute'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/adapters/postgres.rb:274:in `block (2 levels) in execute'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/adapters/postgres.rb:478:in `check_database_errors'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/adapters/postgres.rb:274:in `block in execute'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/connection_pool/threaded.rb:91:in `hold'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/database/connecting.rb:269:in `synchronize'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/adapters/postgres.rb:274:in `execute'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/dataset/actions.rb:1082:in `execute'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/adapters/postgres.rb:570:in `fetch_rows'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/dataset/actions.rb:151:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/dataset/actions.rb:438:in `map'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/dataset/actions.rb:438:in `map'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/dataset/actions.rb:434:in `map'
/app/Rakefile:41:in `block (5 levels) in <top (required)>'
/app/Rakefile:40:in `each'
/app/Rakefile:40:in `block (4 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `load'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:27:in `run'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli.rb:360:in `exec'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli.rb:20:in `dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli.rb:10:in `start'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/exe/bundle:30:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/exe/bundle:22:in `<top (required)>'
/app/vendor/bundle/ruby/2.5.0/bin/bundle:22:in `load'
/app/vendor/bundle/ruby/2.5.0/bin/bundle:22:in `<main>'

Caused by:
PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type double precision: "-"
LINE 1: ..."aqm_records" WHERE ("pm2_5_concentration_ug_per_m3" != '-')
                                                                   ^
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/adapters/postgres.rb:146:in `async_exec'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/adapters/postgres.rb:146:in `block in execute_query'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/database/logging.rb:38:in `log_connection_yield'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/adapters/postgres.rb:146:in `execute_query'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/adapters/postgres.rb:134:in `block in execute'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/adapters/postgres.rb:110:in `check_disconnect_errors'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/adapters/postgres.rb:134:in `execute'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/adapters/postgres.rb:456:in `_execute'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/adapters/postgres.rb:274:in `block (2 levels) in execute'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/adapters/postgres.rb:478:in `check_database_errors'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/adapters/postgres.rb:274:in `block in execute'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/connection_pool/threaded.rb:91:in `hold'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/database/connecting.rb:269:in `synchronize'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/adapters/postgres.rb:274:in `execute'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/dataset/actions.rb:1082:in `execute'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/adapters/postgres.rb:570:in `fetch_rows'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/dataset/actions.rb:151:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/dataset/actions.rb:438:in `map'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/dataset/actions.rb:438:in `map'
/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.7.1/lib/sequel/dataset/actions.rb:434:in `map'
/app/Rakefile:41:in `block (5 levels) in <top (required)>'
/app/Rakefile:40:in `each'
/app/Rakefile:40:in `block (4 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `load'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:27:in `run'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli.rb:360:in `exec'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli.rb:20:in `dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli.rb:10:in `start'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/exe/bundle:30:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/exe/bundle:22:in `<top (required)>'
/app/vendor/bundle/ruby/2.5.0/bin/bundle:22:in `load'
/app/vendor/bundle/ruby/2.5.0/bin/bundle:22:in `<main>'
Tasks: TOP => statistics:temp:pull_request_40:ruby
(See full trace by running task with --trace)

# do post-migration check on console. it's the same, yay!
$ heroku run irb
Running irb on ⬢ westconnex-m4-east-air-quality... up, run.4485 (Free)
irb(main):001:0>         require './database'
=> true
irb(main):002:0>         measurements = %w[pm2_5_concentration_ug_per_m3 pm10_concentration_ug_per_m3 co_concentration_ppm no2_concentration_ppm]
=> ["pm2_5_concentration_ug_per_m3", "pm10_concentration_ug_per_m3", "co_concentration_ppm", "no2_concentration_ppm"]
irb(main):003:0> 
irb(main):004:0>         measurements.each do |measurement|
irb(main):005:1*           values = AqmRecord.map(measurement.to_sym).compact.map(&:to_f)
irb(main):006:1>           puts "#{measurement}: #{(values.sum(0.0) / values.length).round(10)}"
irb(main):007:1>         end
pm2_5_concentration_ug_per_m3: 15.6022786346
pm10_concentration_ug_per_m3: 26.0173114413
co_concentration_ppm: 0.2515300943
no2_concentration_ppm: 0.0147627929
=> ["pm2_5_concentration_ug_per_m3", "pm10_concentration_ug_per_m3", "co_concentration_ppm", "no2_concentration_ppm"]

# compare Ruby calculation with SQL. they're the same, yay!
$ heroku run 'bundle exec rake statistics:temp:pull_request_40:sql'
Running bundle exec rake statistics:temp:pull_request_40:sql on ⬢ westconnex-m4-east-air-quality... up, run.1014 (Free)
pm2_5_concentration_ug_per_m3: 15.6022786346
pm10_concentration_ug_per_m3: 26.0173114413
co_concentration_ppm: 0.2515300943
no2_concentration_ppm: 0.0147627929
```

**Comment by henare** [comment]
Here's the before and after CSVs if we need them https://gist.github.com/henare/57b258e41f8b1c9530ede8be2e5b46a2/revisions

**Comment by equivalentideas** [comment]
> That's now deployed 🎉

Well done @henare 🏆 Great documenting of the process ✨ 🙏

**Pull request merged**
