### PR TITLE
Make scraper script executable

### PR DESCRIPTION
**Pull request by henare**
So we can easily run it from the command line without having to prefix
the command with `ruby`.

### CODE REVIEW

**Comment by equivalentideas** [comment]
Good change, but this doesn't work for me in development:

```
> bundle exec dotenv scraper.rb
bundler: failed to load command: dotenv (/Users/Luke/.rbenv/versions/2.5.0/bin/dotenv)
Errno::ENOENT: No such file or directory - scraper.rb
  /Users/Luke/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/dotenv-2.2.1/lib/dotenv/cli.rb:20:in `exec'
  /Users/Luke/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/dotenv-2.2.1/lib/dotenv/cli.rb:20:in `run'
  /Users/Luke/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/dotenv-2.2.1/bin/dotenv:4:in `<top (required)>'
  /Users/Luke/.rbenv/versions/2.5.0/bin/dotenv:23:in `load'
  /Users/Luke/.rbenv/versions/2.5.0/bin/dotenv:23:in `<top (required)>'

```

Possibly to do with assumption about where `ruby` is? Need solution that works for different ruby version managers :) I'll look more at this later 👍

**Comment by equivalentideas** [comment]
So actually, the problem is that when running a script with dotenv like this, it looks for files relative to itself, and then can't find the file as above. If you run it and provide an absolute reference to the file it works (but that's not a solution).

One way to get this to work is to move the loading of dotenv in to the script with something like:

```
require 'dotenv/load' unless ENV['SCRIPT_ENV'] == 'production'
```

But that also feels a bit nasty? Not sure. Or am I running this wrong? :D

**Comment by henare** [comment]
@equivalentideas my bad! :smiling_imp: I didn't actually test running that command so there was indeed a mistake.

I've added a fixup commit that can be autosquashed once you've tested and approved this PR.

**Comment by equivalentideas** [comment]
We're now running `bundle exec ./scraper.rb` in production ✨

**Pull request merged**
