### PR TITLE
Change column names to include units

### PR DESCRIPTION
**Pull request by equivalentideas**
Needs to update the readme and explain how to run the migration in production.

### CODE REVIEW

**Comment by henare** [comment]
Before we merge this I think we need to resolve #26 and use whatever solution we decide on there in this PR.

**Comment by equivalentideas** [comment]
> Before we merge this I think we need to resolve #26 and use whatever solution we decide on there in this PR.

Once https://github.com/equivalentideas/westconnex_M4_East_Air_Quality_Monitoring/pull/30 is merged, we can adjust this to use the new migrations framework ❤️

**Comment by henare** [comment]
Captured backup `b008` prior to merging this.

**Comment by henare** [comment]
After running the migrations:

```
$ time heroku run 'bundle exec rake db:migrate'
Running bundle exec rake db:migrate on ⬢ westconnex-m4-east-air-quality... up, run.8996 (Free)
Migrating database to latest version

real	0m12.128s
user	0m0.401s
sys	0m0.049s
$
```

I had to `heroku restart` for the model changes to be detected and therefore reflected in the CSV that was downloaded.

**Pull request merged**
